# Generated by Django 5.0.14 on 2026-08-09 14:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to transfer each period.', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_index=True, max_length=10)),
                ('start_date', models.DateField(help_text='Date when recurring payment starts.')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date. If null, runs indefinitely.', null=True)),
                ('next_payment_date', models.DateField(db_index=True, help_text='Date when the next payment is due.')),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of the last successful payment.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, help_text='Consecutive failure count (auto-cancels after threshold).')),
                ('receiver', models.ForeignKey(help_text='The user who receives funds.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_recurring_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who initiates and pays for this recurring payment.', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Payment',
                'verbose_name_plural': 'Recurring Payments',
                'db_table': 'recurring_payments_recurringpayment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='recurringpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='recurring_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringpayment',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('receiver')), _negated=True), name='recurring_payment_no_self_transfer'),
        ),
    ]
