services:

  # Django API
  - type: web
    name: payment-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    dockerBuildArgs:
      - key: REQUIREMENTS_FILE
        value: "production.txt"
    dockerCommand: sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
    healthCheckPath: /api/health/
    autoDeployTrigger: commit

    envVars:
      - key: DEBUG
        value: "False"

      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"

      - key: DATABASE_URL
        fromDatabase:
          name: payment-platform-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: payment-redis
          property: connectionString

      - key: CELERY_BROKER_URL
        fromService:
          type: keyvalue
          name: payment-redis
          property: connectionString

      - key: CELERY_RESULT_BACKEND
        fromService:
          type: keyvalue
          name: payment-redis
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - key: AI_PROVIDER
        value: "groq"

      - key: AI_BASE_URL
        value: "https://api.groq.com/openai/v1"

      - key: AI_MODEL
        value: "openai/gpt-oss-20b"

      - key: AI_API_KEY
        sync: false

      - key: RAZORPAY_KEY_ID
        sync: false

      - key: RAZORPAY_KEY_SECRET
        sync: false

      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: CORS_ALLOWED_ORIGINS
        sync: false

      - key: CSRF_TRUSTED_ORIGINS
        sync: false

  # Free Redis-compatible Key Value
  - type: keyvalue
    name: payment-redis
    plan: free
    region: singapore
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow application connections

databases:

  - name: payment-platform-db
    databaseName: payment_platform
    user: payment_user
    plan: free