# Generated by Django 5.0.14 on 2026-08-09 14:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_reference', models.CharField(db_index=True, help_text='Unique human-readable reference (e.g. TXN-ABC123).', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Direction is inferred from transaction_type.', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment ID for gateway-initiated transactions.', max_length=255, null=True)),
                ('receiver_wallet', models.ForeignKey(blank=True, help_text='Destination wallet. Null for external withdrawals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='wallets.wallet')),
                ('sender_wallet', models.ForeignKey(blank=True, help_text='Source wallet. Null for external deposits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'), models.Index(fields=['-created_at'], name='transaction_created_300c15_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='transaction_amount_positive'),
        ),
    ]
