# Generated by Django 5.0.14 on 2026-08-09 14:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_event_id', models.CharField(db_index=True, help_text="Razorpay's unique event ID.", max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='e.g. payment.captured, payment.failed', max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('payload', models.JSONField(help_text='Full raw webhook payload.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Razorpay Webhook Event',
                'verbose_name_plural': 'Razorpay Webhook Events',
                'db_table': 'payments_razorpay_webhook_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in INR.', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, help_text='Razorpay Order ID (order_...).', max_length=255, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, help_text='Razorpay Payment ID (pay_...).', max_length=255, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='HMAC-SHA256 signature from Razorpay.', max_length=512, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata (e.g. {user_id, payment_reference}).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='payment_amount_positive'),
        ),
    ]
